CREATE TABLE IF NOT EXISTS veiculos (
    id SERIAL PRIMARY KEY,
    veiculo VARCHAR(255) NOT NULL,
    marca VARCHAR(255) NOT NULL,
    ano INTEGER NOT NULL,
    descricao TEXT,
    vendido BOOLEAN NOT NULL,
    created TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    updated TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
    );
